title = "login toml config file"

[base]
    web_addr = "0.0.0.0:9599"
    root_dir = "E:/goproject/community-sig"
    var_dir = "E:/goproject/community-sig"
	heart_max = 30000
	heart_check = 6000
	grpc_addr = "127.0.0.1:8092"
    service_name = "comsig-service"
	peer_service_name = "status-service"
[log_conf]
    project = "community-sig"
    name = "main"
    log_dir  = "log"
    log_level = "info"
    max_day = 7
    rotate_seconds = 36000
    extname=""
[register_center]
    address = ["127.0.0.1:2181"]
    timeout = 5



